version: '2'

services:
  mariadb:
    image: mariadb:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - laravel

  laravel:
    build:
      context: .
      args:
        BUILD_ARGUMENT_ENV: prod
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/html:cached
    depends_on:
      - mariadb
    networks:
      - laravel

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html:ro,cached
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - laravel
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "40001:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    networks:
      - laravel

networks:
  laravel:
    name: laravel
